# Generated by Django 3.1.2 on 2021-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('prep_time', models.CharField(blank=True, max_length=30)),
                ('cook_time', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
            ],
        ),
    ]
