# Generated by Django 3.1.2 on 2021-01-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycb', '0002_auto_20210114_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
